[platformio]
src_dir = .
include_dir = .
build_dir = C:/Users/23167/.platformio/build/CCAirDetector
libdeps_dir = C:/Users/23167/.platformio/libdeps/CCAirDetector

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = huge_app.csv
lib_ldf_mode = deep+

build_src_filter =
  +<*.ino>
  +<*.cpp>
  -<.git/>
  -<.agents/>
  -<.pio/>

lib_deps =
  bodmer/TFT_eSPI
  bblanchon/ArduinoJson@^6.21.5
  arduino-libraries/NTPClient
  mathertel/OneButton
  fastled/FastLED
